info_txt_file = 'infos.txt'
metadata_file = 'metadata.csv'
dates_number = 20
input_dates = 'dates'
standard_search_terms = [" - Copy", "-Background subtraction", "_ORG", " "]
standard_replacements = ["", "", "", "_"]
dapi_str = "dapi"
stack_name = "Stack"
tiff_ext = ".tif"
